/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.9 at Mon Nov  6 11:17:09 2023. */

#include "var_monitor_data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t VarMonitorData_fields[3] = {
    PB_FIELD(  1, STRING  , REPEATED, STATIC  , FIRST, VarMonitorData, head, head, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, VarMonitorData, item, head, &VarMonitorData_Item_fields),
    PB_LAST_FIELD
};

const pb_field_t VarMonitorData_Item_fields[2] = {
    PB_FIELD(  2, DOUBLE  , REPEATED, STATIC  , FIRST, VarMonitorData_Item, data, data, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 *
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(VarMonitorData, item[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_VarMonitorData_VarMonitorData_Item)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for VarMonitorData.item is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
